### ISSUE TITLE
Task view should be generic

### ISSUE THREAD

**Issue by mfitzp** [wooey/django-djangui#14]
I'm working on reorganising the templates a little and noticed that the task view is tied to the celery backend. Am wondering if we want to tie Wooey specifically to celery (I have no problem with this) or implement this in a bit more abstract way? 

For the time being (working up to the merge) I'll probably just hide the celery-specific naming (e.g. urls etc.) so that we can abstract the backend more easily in the future. But just interested in your thoughts.

**Comment by Chris7** [comment]
I haven't really explored other python queuing engines and don't know how generalizable we could make it. Given celery uses decorators, and not all queuing engines may take that approach, it probably isn't easy. In general I'm happy with celery and don't mind being specific to celery. Especially given the bootstrapper sets celery up for you, we've removed the burden from users of setting up their own.

The celery specific naming certainly can go, especially because celery isn't the emphasis, the tasks/results are.

**Comment by mfitzp** [comment]
That's fine... I was thinking about the possibility of people wanting to dispatch jobs to clusters, etc. but having looked around that's probably easier using celery as the engine for it anyway. I'll remove the celery naming (e.g. in urls, views, etc.) but leave the code as-is.
