### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Chris7** [wooey/django-djangui#20]
@mfitzp Do you have any preference for a license? I  just used GPL on djangui since it's the same license on other projects. It seems BSD is the most liberal for open source so I'm fine with that. I personally don't care what we license it under, but wasn't sure if you were under any restrictions for your code.

**Comment by mfitzp** [comment]
I'm fine with either.. I have a general rule of licensing libraries as BSD
(...or MIT...or...) and applications under the GPL mostly due to using
libraries like Qt with them.

Wooey being a web thing is a bit different but our two big dependencies
(django, celery) are both BSD and we specifically want people to be able to
integrate Wooey with their existing systems and/or bundle it with scripts.
GPL doesn't really restrict someone taking the sourcecode and modifying and
running their own service out of it (we'd need the Affero GPL for that!)

So I think BSD is maybe the way to go?

For the future if we do create a hosted service from Wooey (+features+cost)
we would still be free to license those extensions any way we liked on top
(as above). So I can't see BSD-like causing problems.

**Comment by Chris7** [comment]
BSD it is! I'll update our setup to reflect this.
