### ISSUE TITLE
Conditional Field

### ISSUE THREAD

**Issue by streetmapp** [wooey/django-djangui#8]
Looking to have a confirmation field available in certain cases. One way to achieve this that I'm aware of is to have the field always there, and execute some checks that way. Ideally, the field only shows when a particular condition is met.  

The main use case is to prevent accidental execution if ENV = PROD.

Is this a potential feature request?

**Comment by Chris7** [comment]
Are you describing subparsers for argparse?

Like this SO question:
http://stackoverflow.com/questions/9505898/conditional-command-line-arguments-in-python-using-argparse

This sounds like something for the 'clinto' package, which can implement subparser processing. I'll created an issue for that. 

An alternative would be the creation of our own view that allows decision trees to be created with filters..but I'm thinking that is a lot of work and too situational for my liking -- but it might also be something already implemented by some javascript library.

**Comment by streetmapp** [comment]
I believe so, yes. 

Will changes going forward mainly be in this repo, or will your personal django-djangui also be maintained?  As we are still testing, can switch over without much issue.

**Comment by Chris7** [comment]
Good -- I think subparsers are a good way to implement this.

I'm going to be incorporating bug fixes across both, but new features will be biased towards this repo. 

For switching, the backend is mostly django-djangui with a facelift at this point, so you shouldn't have issues with compatibility going forward. The only issue would be a database migration, which I might write a script to handle migrations. Since the table schema will change names it isn't that much of a big deal, just a mapping of djangui->wooey in a script for exporting from the old database and importing the fixtures to the new database.

**Comment by mfitzp** [comment]
Move to the new repo at: https://github.com/wooey/Wooey/issues/24
